### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by skys215** [freefcw/hustoj#43]
When wil the Installation sction will be updated?
I downloaded it, but I cannot install.

Regards,

**Comment by xff252595680** [comment]
I think I get a same error like qhpeklh5959 do .....

Here is my log:

2015-04-26 16:20:42 --- EMERGENCY: HTTP_Exception_404 [ 404 ]: The requested URL hustoj was not found on this server. ~ SYSPATH/classes/Kohana/HTTP/Exception.php [ 19 ] in /var/www/html/hustoj/system/classes/Kohana/Request/Client/Internal.php:79
2015-04-26 16:20:42 --- DEBUG: #0 /var/www/html/hustoj/system/classes/Kohana/Request/Client/Internal.php(79): Kohana_HTTP_Exception::factory(404, 'The requested U...', Array)
#1 /var/www/html/hustoj/system/classes/Kohana/Request/Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#2 /var/www/html/hustoj/system/classes/Kohana/Request.php(997): Kohana_Request_Client->execute(Object(Request))
#3 /var/www/html/hustoj/index.php(105): Kohana_Request->execute()
#4 {main} in /var/www/html/hustoj/system/classes/Kohana/Request/Client/Internal.php:79

**Comment by Foxprodev** [comment]
Same error. Should we install kohana?

**Comment by freefcw** [comment]
@xff252595680 @Foxprodev 

Please show me your nginx or apache site config file

**Comment by Foxprodev** [comment]
@freefcw Already fixed it,  AllowOverride in this directory.
But how to fix http://stackoverflow.com/questions/4624726/http-error-302-using-uploadify?
In firefox, safari, os x browsers.
